server:
  port: 7581
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024


spring:
  application:
    name: Shop Solution

  data:
    mongodb:
      host: 127.0.0.1
      database: shop
      port: 27017


  jackson:
    serialization.indent_output: true


  messages:
    basename: i18n/messages


  thymeleaf:
    mode: HTML
    cache: false


  mail:
    host: localhost
    port: 25
    username:
    password:

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
#      location: /images